version: "3.9"
services:
  backend:
    build: ./Media.Api/
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: always
    networks:
      - backend_network
#    env_file: .env
    
  backend_auth:
    build: ./Authentication.Api/
    ports:
      - "5090:5090"
    depends_on:
      - postgres
    restart: always
    networks:
      - backend_network
#    env_file: .env
  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - backend_auth
    ports:
      - "80:80"
    restart: always
    networks:
      - backend_network

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Abc123456#
#    env_file: .env
    ports:
      - "55432:5432"
    restart: always
    volumes:
      - /postgresql_data:/var/lib/postgresql
    networks:
      - backend_network

  mongo:
    container_name: mongodb
    image: mongo
    ports: 
      - 18005:27017
#    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    restart: always
    volumes:
      - './data:/data/db'
    networks:
      - backend_network
      
networks:
  backend_network:
